sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cPUVIkYfHJIOpeCGlMIkCdEuDG7PO7jVsw/A7JtTY3sssIBGUhG9qoA+IxPnT1uQaAVyAOM7s6E984E2DyCmravy//63+YW7I2oilqXaamoX7QwfFxpOl49jo2wxi4/PLAlWc5fngOyKjFnhePm9tPHkZVg9+cGT98eqUzNZgMAG8vgxR+Elv+awQDSMhNY3EFmtSrCNb4shwBhiXNn4TD8QiUhAX1AiRkROWh4qAPpYmDd3dLpqMe9yjfhBnD3oUiSTZubWTZcL10SRj0xzkSQUqX1nRhcjFj+syDwyf4DucZIFfbucNktqbJRkiJ7PyjqDEDgsX/HYWbiUK+U2nnTj7t7o8lm4ovVAwR31bDLdUIQHYaakvs6eZwt4UbrgMDYmZLVlkv2FQ0dNd9tPRbkxqkKJePZucCjWEqumDpY1yLVkMTs6Lt6VLYeLitfVhXsvVHqyl1esDHZguG2K9uGznAZaqMGKsHGWK3F01r6m4dOhhCd89HvcTtxIQNU8MJXgVm3SQH5GWsjQERq2fl8M17D9eAcI8+uR9Ia4dYqaEnl+VYM7N9rI199olTK+Vx/EAeFMlCQaclPlX83lNv1g0JXTRH4/Qhq3NxLNV4uOtVbsW8NRFvZyptyJGqDvoe7z1TqzxnxnwRA+0jsSOqYmPJ2vmtaTkHKwznk88xI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Appendicitis-The-Etiology-Hygenic-and-Dietetic-Treatment_4314
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy